### ISSUE TITLE
Status of the project and difference with VideoRoom

### ISSUE THREAD

**Issue by ndeber** [michaelfranzl/janus-rtpforward-plugin#1]
Hi Michael,

We are working with Janus Video Plugin specifically to forward the stream in RTP to a downstream GStreamer pipeline, so I was very happy to see your plugin !

We are experiencing some quality issues in the stream gstreamer receives, and you seem to have encountered the same kind of issues. 
I was wondering if that was something your plugin help you improve/debug?

Thanks,
nicolas

**Comment by michaelfranzl** [comment]
I don't know if I have encountered the same issues which you have encountered. The only issue I encountered was dropped UDP packets due to unreliable networks, and video decoder's difficulties dealing with it, but that's not specific to any kind of software.

I don't know if my plugin can help you debug your issues. I guess it can when simplicity helps.
