### ISSUE TITLE
Make fails (for 0.9.4 version)

### ISSUE THREAD

**Issue by geeksha** [michaelfranzl/janus-rtpforward-plugin#5]
I was trying to compile your plugin for janus-gateway 0.9.4 and gives me an erro in make step. Here the log:

https://gist.github.com/geeksha/be22ed493ea863c238c82977da6ea320#file-gistfile1-txt

I hope it's usefel for you

One question regarding your approach: why not using directly the rtp_forwarding feature in videoroom plugin? What is the improvement added for your approach? I am researching different ways to do rtp_forwarding from WebRTC source to plain RTP. 

Thanks in advance!

**Comment by michaelfranzl** [comment]
Your error log contains:

```
janus_rtpforward.c:581:5: error: too many arguments to function ‘gateway->relay_rtcp’
  581 |     gateway->relay_rtcp(session->handle, 1, buf, remblen);
      |     ^~~~~~~
make: *** [Makefile:454: janus_rtpforward.lo] Error 1
```

It seems you are trying to compile `janus-rtpforward-plugin` version 0.4 (which was made for `janus-gateway` version 0.4) against `janus-gateway` 0.9. This will not work because `janus-gateway` version 0.9 introduced [breaking changes](https://github.com/meetecho/janus-gateway/pull/1884) the plugin API.

Please re-try an up-to-date master branch which recently [received](https://github.com/michaelfranzl/janus-rtpforward-plugin/pull/4) support for `janus-gateway` version 0.9.

I addressed your question about the videoroom plugin in an update to the README. See https://github.com/michaelfranzl/janus-rtpforward-plugin/commit/ed8e87fb029af7355b7a6b03f78dba3fbb81e7f8

**Comment by geeksha** [comment]
Many thanks for updating the README. This was a really clear explanation regarding your approach.
I was retrying compilation and it was compiling without any problem. I will check a little the behavior and the differences with videoroom testing both :)
